apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multidimpodautoscalers.autoscaling.k8s.io
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  annotations:
    "api-approved.kubernetes.io": "unapproved.*"
spec:
  group: autoscaling.k8s.io
  scope: Namespaced
  names:
    plural: multidimpodautoscalers
    singular: multidimpodautoscaler
    kind: MultidimPodAutoscaler
    shortNames:
    - mpa
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          spec:
            type: object
            required: ["scaleTargetRef"]
            properties:
              scaleTargetRef:
                type: object
                properties:
                  kind:
                    type: string
                  name:
                    type: string
                  apiVersion:
                    type: string
              goals:
                type: object
                properties:
                  metrics:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: ["Resource"]
                        resource:
                          type: object
                          properties:
                            name:
                              type: string
                              enum: ["cpu"]
                            target:
                              type: object
              constraints:
                type: object
                properties:
                  global:
                    type: object
                    properties:
                      minReplicas:
                        type: integer
                        minimum: 0
                      maxReplicas:
                        type: integer
                        minimum: 0
                      requests:
                        type: object
                        properties:
                          minAllowed:
                            type: object
                          maxAllowed:
                            type: object
                  pod:
                    type: object
                    properties:
                      requests:
                        type: object
                        properties:
                          minAllowed:
                            type: object
                          maxAllowed:
                            type: object
                  containerControlledResources:
                    type: array
                    items:
                      type: string
                      enum: ["memory"]
                  container:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        requests:
                          type: object
                          properties:
                            minAllowed:
                              type: object
                            maxAllowed:
                              type: object
              policy:
                type: object
                properties:
                  updateMode:
                    type: string
                    enum: ["Off", "Auto"]
